#!/usr/bin/env python3
"""Compile the combined intro TikZ figure to PDF."""

import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
TEX_FILE = SCRIPT_DIR / "combined_intro.tex"
PDF_FILE = SCRIPT_DIR / "combined_intro.pdf"


def compile_tikz():
    """Compile the TikZ source to PDF using pdflatex."""
    if not TEX_FILE.exists():
        print(f"Error: {TEX_FILE} not found")
        return False

    print(f"Compiling {TEX_FILE.name}...")

    try:
        result = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", TEX_FILE.name],
            cwd=SCRIPT_DIR,
            capture_output=True,
            timeout=30
        )

        if result.returncode == 0:
            print(f"Generated: {PDF_FILE}")
            print(f"  Size: {PDF_FILE.stat().st_size / 1024:.1f} KB")
            return True
        else:
            print("Compilation failed!")
            # Show relevant error lines
            output = result.stdout.decode()
            for line in output.split('\n'):
                if '!' in line or 'Error' in line:
                    print(f"  {line}")
            return False

    except FileNotFoundError:
        print("Error: pdflatex not found. Run inside 'nix develop' or install texlive.")
        return False
    except subprocess.TimeoutExpired:
        print("Error: Compilation timed out")
        return False


def cleanup():
    """Remove auxiliary files generated by pdflatex."""
    for ext in ['.aux', '.log']:
        aux_file = SCRIPT_DIR / f"combined_intro{ext}"
        if aux_file.exists():
            aux_file.unlink()


def main():
    print("=" * 50)
    print("Combined Intro Figure Generator")
    print("=" * 50)
    print()

    success = compile_tikz()

    if success:
        cleanup()
        print()
        print("Figure ready for LaTeX!")
        print(f"  Use: \\includegraphics[width=\\columnwidth]{{figures/combined_intro.pdf}}")
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
